[versions]
agp = "8.13.1"
activity = "1.12.1"
annotation = "1.9.1"
androidplotCore = "1.5.11"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
converterGson = "3.0.0"
core = "1.17.0"
coreKtx = "1.17.0"
circleindicator = "2.1.6"
circleprogress = "1.2.1"
espressoCore = "3.7.0"
extJunit = "1.3.0"
firebaseBom = "34.6.0"
glide = "5.0.5"
googleApiClientAndroid = "2.8.1"
googleApiServicesDrive = "v3-rev20220815-2.0.0"
googleApiServicesSheets = "v4-rev20220927-2.0.0"
googleHttpClientAndroid = "2.0.2"
googleHttpClientJackson2 = "2.0.2"
junit = "4.13.2"
junitVersion = "1.3.0"
legacySupportV4 = "1.0.0"
lifecycleLivedataKtx = "2.10.0"
lifecycleViewmodelKtx = "2.10.0"
localbroadcastmanager = "1.1.0"
material = "1.13.0"
mpandroidchart = "v3.1.0"
multiwaveheader = "v1.0.0-alpha-4"
navigationFragment = "2.9.6"
navigationUi = "2.9.6"
okhttp = "5.3.2"
orgEclipsePahoAndroidService = "1.1.1"
orgEclipsePahoClientMqttv3 = "1.2.5"
playServicesAuth = "21.4.0"
playServicesBase = "18.9.0"
playServicesBasement = "18.9.0"
playServicesTasks = "18.4.0"
retrofit = "3.0.0"
straiberryCharts = "1.1.0"
switchbutton = "1.0.4"

[libraries]
activity = { module = "androidx.activity:activity", version.ref = "activity" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidplot-core = { module = "com.androidplot:androidplot-core", version.ref = "androidplotCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
circleindicator = { module = "me.relex:circleindicator", version.ref = "circleindicator" }
circleprogress = { module = "com.github.lzyzsd:circleprogress", version.ref = "circleprogress" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
core = { module = "androidx.core:core", version.ref = "core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "extJunit" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-api-client-android = { module = "com.google.api-client:google-api-client-android", version.ref = "googleApiClientAndroid" }
google-api-services-drive = { module = "com.google.apis:google-api-services-drive", version.ref = "googleApiServicesDrive" }
google-api-services-sheets = { module = "com.google.apis:google-api-services-sheets", version.ref = "googleApiServicesSheets" }
google-http-client-android = { module = "com.google.http-client:google-http-client-android", version.ref = "googleHttpClientAndroid" }
google-http-client-jackson2 = { module = "com.google.http-client:google-http-client-jackson2", version.ref = "googleHttpClientJackson2" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
localbroadcastmanager = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "localbroadcastmanager" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
multiwaveheader = { module = "com.github.BharathKSunil:MultiWaveHeader", version.ref = "multiwaveheader" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationUi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
org-eclipse-paho-android-service = { module = "org.eclipse.paho:org.eclipse.paho.android.service", version.ref = "orgEclipsePahoAndroidService" }
org-eclipse-paho-client-mqttv3 = { module = "org.eclipse.paho:org.eclipse.paho.client.mqttv3", version.ref = "orgEclipsePahoClientMqttv3" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBase" }
play-services-basement = { module = "com.google.android.gms:play-services-basement", version.ref = "playServicesBasement" }
play-services-tasks = { module = "com.google.android.gms:play-services-tasks", version.ref = "playServicesTasks" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
straiberry-charts = { module = "com.github.STRAIBERRY-AI-INC:Straiberry-charts", version.ref = "straiberryCharts" }
switchbutton = { module = "com.github.iielse:switchbutton", version.ref = "switchbutton" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }